// src/components/PreviewSizeSlider.vue
<template>
<div class="inline-flex items-center gap-1 bg-white dark:bg-gray-800 px-2 py-1 rounded-lg shadow-sm">
  <Button
    icon="pi pi-minus"
    @click="updateValue(modelValue - step)"
    :disabled="modelValue <= min"
    class="p-button-text p-button-sm !p-0.5 !w-6 !h-6"
    :class="{ 'p-button-secondary': darkMode }"
    title="Decrease size"
  />
  
  <Slider
    v-model="localValue"
    :min="min"
    :max="max"
    :step="step"
    class="w-12"
  />
  
  <Button
    icon="pi pi-plus"
    @click="updateValue(modelValue + step)"
    :disabled="modelValue >= max"
    class="p-button-text p-button-sm !p-0.5 !w-6 !h-6"
    :class="{ 'p-button-secondary': darkMode }"
    title="Increase size"
  />
</div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import Button from 'primevue/button'
import Slider from 'primevue/slider'

const props = defineProps<{
  modelValue: number
  min?: number
  max?: number
  step?: number
  darkMode?: boolean
}>()

const emit = defineEmits<{
  'update:modelValue': [value: number]
}>()

const localValue = computed({
  get: () => props.modelValue,
  set: (value) => emit('update:modelValue', value)
})

const updateValue = (value: number) => {
  const newValue = Math.max(props.min ?? 150, Math.min(props.max ?? 400, value))
  emit('update:modelValue', newValue)
}
</script>

<style scoped>
:deep(.p-slider) {
  height: 0.25rem;
}

:deep(.p-slider .p-slider-handle) {
  height: 0.75rem;
  width: 0.75rem;
  margin-top: -0.25rem;
  margin-left: -0.375rem;
}

:deep(.p-button.p-button-sm) {
  padding: 0.25rem;
}

:deep(.p-button.p-button-sm .p-button-icon) {
  font-size: 0.75rem;
}
</style>

// src/components/PreviewSizeSlider.tsx
import React from 'react';
import { Minus, Plus, Maximize2, Minimize2 } from 'lucide-react';

interface PreviewSizeSliderProps {
  value: number;
  onChange: (value: number) => void;
  min: number;
  max: number;
  step?: number;
}

export function PreviewSizeSlider({
  value,
  onChange,
  min,
  max,
  step = 10
}: PreviewSizeSliderProps) {
  const percentage = ((value - min) / (max - min)) * 100;

  return (
    <div className="flex items-center gap-4 bg-white px-4 py-2 rounded-lg shadow-sm">
      <button
        onClick={() => onChange(min)}
        className="p-1.5 rounded-lg hover:bg-gray-100 transition-colors"
        title="Minimum size"
      >
        <Minimize2 className="w-4 h-4" />
      </button>
      
      <button
        onClick={() => onChange(Math.max(min, value - step))}
        className="p-1.5 rounded-lg hover:bg-gray-100 transition-colors"
        title="Decrease size"
      >
        <Minus className="w-4 h-4" />
      </button>
      
      <div className="relative w-32 h-6">
        <input
          type="range"
          min={min}
          max={max}
          step={step}
          value={value}
          onChange={(e) => onChange(Number(e.target.value))}
          className="absolute w-full h-2 top-2 appearance-none bg-gray-200 rounded-full outline-none cursor-pointer"
          style={{
            background: `linear-gradient(to right, #3b82f6 0%, #3b82f6 ${percentage}%, #e5e7eb ${percentage}%, #e5e7eb 100%)`
          }}
        />
        <div className="absolute -top-6 left-0 right-0 text-center">
          <span className="text-xs text-gray-500">{value}px</span>
        </div>
      </div>
      
      <button
        onClick={() => onChange(Math.min(max, value + step))}
        className="p-1.5 rounded-lg hover:bg-gray-100 transition-colors"
        title="Increase size"
      >
        <Plus className="w-4 h-4" />
      </button>
      
      <button
        onClick={() => onChange(max)}
        className="p-1.5 rounded-lg hover:bg-gray-100 transition-colors"
        title="Maximum size"
      >
        <Maximize2 className="w-4 h-4" />
      </button>
    </div>
  );
}
